### ISSUE TITLE
Data check: Why is camm at debian.org not detected as a Debian developer?

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-greenhouse#17]
http://greenhouse-daveeloo.dotcloud.com/contributors/camm@debian.org says they're not a DD, but they are uploading with @debian.org

Is it a data problem in the debian-email-addresses file? Or something else?

**Comment by daveeloo** [comment]
debian-email-addresses file lists his email as camm@enhanced.com

**Comment by daveeloo** [comment]
This was fixed with issue #18. The Debian email address file doesn't have his at debian.org email.
