### ISSUE TITLE
Deduplicate email addresses using GPG fingerprints

### ISSUE THREAD

**Issue by daveeloo** [openhatch/oh-greenhouse#19]
Add an extra column to People that is original_email with default being null and add extra column to Upload that is original_email_changer (make it an EmailField instead of TextField while at it) and change the code for build_people_db to deal with this. Add an "unify" button on the person page that pops up a div with a JQuery autocomplete with names. Have algorithm that will make these changes.

**Comment by daveeloo** [comment]
Potential heuristics:
most duplicated identity emails have the same name different domain

notes:
use fingerprint not key_id
if uploader and changer are the same must be a debian developer
same name different email bigger problem as person gets more experienced

**Comment by paulproteus** [comment]
Assigning to next milestone, b/c we talked about it at Monday meeting.

**Comment by daveeloo** [comment]
The fingerprint is for the sponsor, which means it is not useful because the People objects are built from email_changer.
