### ISSUE TITLE
Check for "Is this person a Debian Developer?" should not be in a view

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-greenhouse#25]
24c544f5311718cbc45d9ce15c250923bd41af35 introduces a change where we "re.search()" from within a view.

This basically suggests the data in the table has the wrong content -- that is, ubuntu_dev is False but should be set to True.

Rather than filtering at view time, we should come up with a new strategy so we fix the data in the database instead.

**Comment by daveeloo** [comment]
This is in a management command, but the problem is it doesn't fix existing people. Should be changed to fix that.

**Comment by daveeloo** [comment]
Commit 06e35 fixes this now.

**Comment by paulproteus** [comment]
Assigning to next milestone, just b/c we mentioned it as a possibility during the Monday meeting. Yay for having already done it!
