### ISSUE TITLE
Remove is_active from models.py

### ISSUE THREAD

**Issue by daveeloo** [openhatch/oh-greenhouse#27]

**Comment by daveeloo** [comment]
Removed references from person.html and first_timers.html, changed the model to remove is_active and performed a schema migration.

**Comment by paulproteus** [comment]
I don't see a schema migration in this commit; can you link to the commit that adds it?

**Comment by daveeloo** [comment]
Accidentally added it to this commit:
https://github.com/openhatch/oh-greenhouse/commit/c12a51379f20ef959598af70e6c54c90b70aaedc

**Comment by paulproteus** [comment]
Cool. In the future, do try to keep model changes and their migrations together, and not sprinkle them around.
