### ISSUE TITLE
Support finding out if People are Debian developers

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-greenhouse#3]
write some code to use the list of Debian email addresses to indicate if People objects are Debian Developers or not

**Comment by paulproteus** [comment]
https://github.com/openhatch/oh-greenhouse/blob/master/greenhouse/debian-emails has a list of all debian email addresses.

**Comment by paulproteus** [comment]
Please provide a terminal transcript that this works properly.

**Comment by paulproteus** [comment]
In particular:

I want to see a copy-pasted terminal transcript where you do a Django ORM query within a "manage.py shell" that shows that at least one person in the database is properly marked as a Debian developer, and that one person is properly marked not as one.

**Comment by daveeloo** [comment]
> > > from uploads.models import People
> > > all_people = People.objects.all()
> > > debian_emails = set()
> > > dat_people = set()
> > > for p in all_people:
> > > ...     dat_people.add(p.email)
> > > ... 
> > > for p in open('debian-emails'):
> > > ...     debian_emails.add(p.strip())
> > > ... 
> > > deb_devs = dat_people.intersection(debian_emails)
> > > len(deb_devs)
> > > 619
> > > is_dd = all_people[63]
> > > is_dd.name
> > > u'Mark W. Eichin'
> > > is_dd.email
> > > u'eichin@thok.org'
> > > is_dd.email in deb_devs
> > > all_people[213].name
> > > u'Christian Hammers'
> > > all_people[213].email
> > > u'ch@xeniac.westend.com'
> > > all_people[213].email in deb_devs
> > > False
