### ISSUE TITLE
Data sanity-check: First timer

### ISSUE THREAD

**Issue by paulproteus** [openhatch/oh-greenhouse#8]
Is Andrey Rahmatullin really a "First timer"? What does first-timer mean in this context?

**Comment by andrewsomething** [comment]
As http://greenhouse-daveeloo.dotcloud.com/contributors/first_timers.html still looks empty, I assume you mean in the "dashboard" on the front page. The code that generates that is the `dashboard` function in `views.py` starting on line 240 (at least in the "upstream" DAT-Overview"), but I think your problem is in the one of the managment commands that imports the data from UDD as Andrey only has two total uploads as far as greenhouse is concerned.

**Comment by daveeloo** [comment]
This is strange. The last upload is distributed only among a few years.

> > > from uploads.models import People
> > > from collections import Counter
> > > ppl = People.objects.all()
> > > cnt = Counter()
> > > for p in ppl:
> > > ...     cnt[p.last_upload.timestamp.year] += 1
> > > ... 
> > > cnt
> > > Counter({2002: 564, 2013: 504, 2000: 109})

**Comment by daveeloo** [comment]
Andrey is technically a first-timer in the system, going to check the management commands for errors:

> > > People.objects.get(email='wrar@wrar.name')
> > > <People: People object>
> > > andrey = People.objects.get(email='wrar@wrar.name')
> > > andrey.total_uploads
> > > 2

**Comment by andrewsomething** [comment]
Compare that to this query in UDD:

```
udd=> select count(*) from upload_history where changed_by_email = 'wrar@wrar.name';
count 
-------
   34
(1 row)
```

**Comment by daveeloo** [comment]
Hrmm ok I just ran the query on the UDD on my local computer with this result. 

udd=# select count(*) from upload_history where changed_by_email = 'wrar@wrar.name' ;

## count

```
 2
```

 (1 row)

So the problem isn't with the code, it's with the data. I can't access the dotcloud server here (at the Mozilla offices with network restrictions) but will do that when I go home to confirm. I got the local data dump from the Debian site and the dotcloud data dump paulproteus put on the openhatch servers.

**Comment by paulproteus** [comment]
Interesting... this probably means vm3.openhatch.org has broken data somehow.

I propose we (soon) transition to using my public UDD mirror. I will polish that up tomorrow (Thu) daytime and share the info with you there @daveeloo 

Also, if we're going to keep working at the Mozilla office you should get in the habit of setting up your tunnels. See you there, anyway!
