### ISSUE TITLE
Sample email templates linked from web app to debian wiki

### ISSUE THREAD

**Issue by daveeloo** [openhatch/oh-greenhouse#9]

**Comment by paulproteus** [comment]
D'oh, I guess this up to either me or @paultag or maybe @andrewsomething should do, rather than being something just @daveloo should do.

Well it should probably wait until the UI is more clear, so waiting on #12 and #10 and #11 .

But then maybe I can get one of you two try writing up these email templates; especially @andrewsomething since you presumably have some similar text from Ubuntu.

**Comment by andrewsomething** [comment]
In Ubuntu, we've been using the initial contact in order to get feedback on the contributor's experience. This is the template we start with:

> Hello $Name,
> 
> I’m writing to you in my role as a member of Ubuntu's Developer Advisory Team
> (https://wiki.ubuntu.com/DeveloperAdvisoryTeam). First of all I’d like to thank you for the great work you have
> put into Ubuntu. It’s work like yours that makes Ubuntu better for millions of users.
> 
> The second reason I’m mailing you is because I wanted to ask for your feedback about your experience. It’s
> important to us to find out more about what could be generally improved in the development experience.
> 
> So if you have a bit of time, would you mind answering these questions for us?
> 
> What was your general experience with Ubuntu development like?
> What did you like about it?
> What do you feel could be improved?
> 
> Please let me know if you have any questions at all. Also if you are looking for information about a specific
> team or interest of yours, I’m happy to help out.
> 
> Thanks again for your involvement in Ubuntu! Keep up the good work!
> 
> On behalf of the Developer Advisory Team, 

I just use this as a rough template though. 

Here's an example of how we've reported this feedback:

http://people.ubuntu.com/~andrewsomething/dat/New_Contributor_Feedback_12.04.pdf

The main goal though is to provide the contributor with a point of contact.

**Comment by daveeloo** [comment]
A sample one I'm putting here for the record.

Hi,

You are receiving this mail because you recently had your first package
accepted in Debian. First, congratulations, and thank you for contributing
to Debian!

In order to improve Debian's ability to welcome new contributors, I'd
like to ask you a few questions about your own experience. Long-time
members of the Debian community tend to forget how the process of
getting involved in the project feels, and feedback from people who
recently went through the process would be really useful.

I will write and publish a summary of the collected answers. Your
individual answers will not be made public, but might be shared with
other DDs. Please be clear if you mention something that you prefer
not to have shared too widely.

So, here are the questions:

Q1: Can you (briefly) introduce yourself? What motivated you to
   start contributing to Debian? What are you (trying to) contribute
   to in Debian?

Q2: What are your reasons for starting to contribute to Debian _now_? Why
   didn't you start before? :)

Q3: What were the biggest surprises you had while going through the process?

Q4: What did you find most difficult?

Q5: Here are some ideas that have been mentioned, aimed at making it
   easier for new people to start contributing to Debian. Could you
   comment on them? If already implemented, would they have helped you?
a) have clearer lists of easy bugs and tasks, suitable for new contributors,
  so that people can learn about Debian by working on them
b) have a "contributors' frontdesk" where people can describe their skills,
  and get suggestions of areas of Debian where they can help
c) develop internship programs (think of Google Summer of Code)
d) develop peer-mentoring, where an experienced person guides a new
  contributor
e) do localized versions of debian-mentors (French, German, Spanish, ...),
  where new contributors can ask questions about packaging
f) organize IRC schools/seminars about packaging

Q6: What other idea should be implemented, or what should be changed,
   that would have made your life easier?

Q7: Can I publicly list your name to thank you for participating in this
   survey?

Thanks!

**Comment by paulproteus** [comment]
I put paultag's version here: https://wiki.debian.org/GreeetingForNewContributors

and am marking this as resolved.
